vk:
  access:
    userId: {USER_ID}
    accessToken: {ACCESS_TOKEN}
  data:
    groupId: -211236262
    numberOfPosts: 100

scheduled:
  cron: "0/30 * * * * *"

application:
  domain: https://tgsupbot.reliab.tech

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: {DATASOURCE_USERNAME}
    password: {DATASOURCE_PASSWORD}
    url: {DATASOURCE_URL}
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

#server:
#  servlet:
#    context-path: /admin/api/vk